name: clt #
version: '0.4' # 
summary: command line tools for snappy #
description: command line tools for snappy lspci lsusb dmidecode #
grade: devel # 
confinement: devmode #

apps:
    lspci:
        command: usr/bin/lspci
        plugs: [hardware-observe]
    lsusb:
        command: usr/bin/lsusb
        plugs: [hardware-observe]
    dmidecode:
        command: usr/sbin/dmidecode
        plugs: [hardware-observe]
    lshw:
        command: usr/bin/lshw
        plugs: [hardware-observe]
    hwinfo:
        command: usr/sbin/hwinfo

parts:
    pciutils:
        plugin: nil 
        stage-packages:
            - pciutils 
        snap:
            - -usr/share/doc
            - -usr/share/man
    usbutils:
        plugin: nil
        stage-packages:
            - usbutils
        snap:
            - -usr/share/doc
            - -usr/share/man
    dmidecode:
        plugin: nil
        stage-packages:
            - dmidecode
        snap:
            - -usr/share/doc
            - -usr/share/man
    lshw:
        plugin: nil
        stage-packages:
            - lshw
        snap:
            - -usr/share/doc
            - -usr/share/man

    hwinfo:
        plugin: nil
        stage-packages:
            - hwinfo
        snap:
            - -usr/share/doc
            - -usr/share/man






