#!/bin/bash

echo "----------"
echo "----------"
echo ""
cat /sys/devices/virtual/dmi/id/sys_vendor 
cat /sys/devices/virtual/dmi/id/product_name
cat /sys/devices/virtual/dmi/id/product_serial
echo ""
echo "--- BIOS Information ---"
cat /sys/devices/virtual/dmi/id/bios_vendor
cat /sys/devices/virtual/dmi/id/bios_date
cat /sys/devices/virtual/dmi/id/bios_version
echo ""
echo "--- Processor Information ---"
cat /proc/cpuinfo | grep 'name'| uniq | awk '{print $4" "$5" "$6" "$7" "$8" "$9}'
echo ""
echo "----------"
echo "----------"

