#!/bin/bash
# This shell file will pull information from the system
# email = <chad_young@dell.com>

clear
echo ""
echo ""
echo "------------------------------"
echo -ne "System Mfg:	"
cat /sys/devices/virtual/dmi/id/board_vendor
echo -ne "Model:		"
cat /sys/devices/virtual/dmi/id/board_name

echo ""
echo ""
echo "------------------------------"
echo ""
echo ""
