#!/bin/bash
# This shell file will pull information from the system
# email = <chad_young@dell.com>

clear
echo ""
echo ""
echo "==============================="
echo ""
echo ""
echo -ne "System Mfg:	"
cat /sys/devices/virtual/dmi/id/board_vendor
echo -ne "Model:		"
cat /sys/devices/virtual/dmi/id/board_name
echo ""
echo -ne "BIOS Mfg:	"
cat /sys/devices/virtual/dmi/id/bios_vendor
echo -ne "BIOS Date:	"
cat /sys/devices/virtual/dmi/id/bios_date
echo -ne "BIOS Version:	"
cat /sys/devices/virtual/dmi/id/bios_version
echo ""
echo -ne "Linux Info:	"
uname -a
echo ""
echo "---------- Snaps installed ----------"
snap list
echo ""
echo ""
echo "==============================="
echo ""
echo ""
