name: i2ctools # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: tools for i2c # 79 char long summary
description: |
  This is a snap for i2c devices

#
# This yaml file compile on snapcraft 2.31
#

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots


apps:
  i2cdetect:
    command: /usr/sbin/i2cdetect
    plugs: [hardware-observe]
  
  i2cdump:
    command: /usr/sbin/i2cdump
    plugs: [hardware-observe]
    
  i2cget:
    command: /usr/sbin/i2cget
    plugs: [hardware-observe]
    
  i2cset:
    command: /usr/sbin/i2cset
    plugs: [hardware-observe]

parts:
  i2ctools:
    plugin: nil
    stage-packages:
      - i2c-tools
      - libi2c-dev

    # snap is now prime
    prime:
      - -usr/share/doc
      - -usr/shar/man

