name: hello-world-cpp # the name of the snap
version: 0.0.1  # the version of the snap
summary: A CPP hello world program # 79 char long summary
description: A program in CPP that says Hello World! # A longer description for the snap

apps:
    run:
        command: Hello

parts:
    build:
        plugin: make
        source: .

#        files: 
#            bin/hello.cpp.run: bin/hello.cpp.run
