name: hello-world-py # you probably want to 'snapcraft register <name>'
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: simple HW program in python # 79 char long summary
description: simple HW program in python
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots



apps:



parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
